### PR TITLE
Buildpacks support

### PR DESCRIPTION
**Pull request by marek-nogiec**
support for setting custom buildpacks

### CODE REVIEW

**Comment by kwasniew** [comment]
@marek-nogiec  sorry for late integration. 
finally published to npm as heroin-js@1.15.0

**Comment by marek-nogiec** [comment]
@kwasniew np, glad to hear :)

**Comment by kwasniew** [comment]
@marek-nogiec  I'm not sure if the yarn file should be updated as some other changes have been made in the meantime. Installing yarn now as I haven't used it before.

**Comment by marek-nogiec** [comment]
@kwasniew I must've added it by mistake, feel free to remove it if any build fails

**Pull request merged**
